from __future__ import annotations

import json
from pathlib import Path
from typing import Any

REGISTRY = Path("C:/Users/maasa/.codex/route_memory/route-memory.json")
SCHEMA = Path("C:/Users/maasa/.codex/route_memory/route-memory.schema.json")
POINTER_MAP = Path("C:/Users/maasa/.codex/foundation/context_offloads/research_x/pointer-map.json")


def _registry() -> dict[str, Any]:
    return json.loads(REGISTRY.read_text(encoding="utf-8"))


def _zip_upload_route() -> dict[str, Any]:
    routes = {
        route["route_id"]: route
        for route in _registry()["routes"]
    }
    return routes["chatgpt.visible_web.local_zip_upload.codex_desktop.clipboard_attachment.v1"]


def test_route_memory_registry_has_required_control_plane_shape() -> None:
    data = _registry()
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    pointer_paths = {
        entry["artifact_path"]
        for entry in json.loads(POINTER_MAP.read_text(encoding="utf-8"))["entries"]
    }

    assert schema["title"] == "Codex Route Memory Registry"
    assert data["schema_version"] == schema["properties"]["schema_version"]["const"] == 1
    assert data["not_evidence"] is True
    assert REGISTRY.as_posix() in pointer_paths
    assert SCHEMA.as_posix() in pointer_paths
    assert len({route["route_id"] for route in data["routes"]}) == len(data["routes"])

    for route in data["routes"]:
        assert route["not_evidence"] is True
        assert route["positive_triggers"]
        assert route["negative_triggers"]
        assert route["canonical_first_action"]
        assert route["known_failed_routes"]
        assert route["success_verification"]
        assert route["gates"]
        assert route["source_pointers"]


def test_chatgpt_zip_upload_route_prefers_clipboard_attachment_first() -> None:
    route = _zip_upload_route()
    first_action = route["canonical_first_action"]
    failed = "\n".join(route["known_failed_routes"])
    verification = "\n".join(route["success_verification"])

    assert "tab.clipboard.write" in first_action
    assert "application/zip" in first_action
    assert "Zip アーカイブ" in first_action
    assert "submit exactly once" in first_action
    assert "askWithFiles" not in first_action
    assert "file chooser" not in first_action.lower()
    assert "askWithFiles" in failed
    assert "file chooser" in failed
    assert "raw CDP" in failed
    assert "ZIP chip" in verification


def test_route_memory_registry_does_not_grant_external_permissions() -> None:
    data = _registry()
    text = json.dumps(data, ensure_ascii=False)

    assert "not evidence" in data["purpose"]
    assert "does not grant" in text
    assert "provider API" in text
    assert "browser approval" in text
    assert "MCP" in text
    assert "install" in text


def test_chatgpt_zip_upload_route_is_not_selected_for_downloads() -> None:
    route = _zip_upload_route()
    negatives = "\n".join(route["negative_triggers"])

    assert "download ZIP generated by ChatGPT" in negatives
    assert "latest ZIP download" in negatives
    assert "latest generated file" in negatives
    assert "OpenAI API" in negatives
